- name: create aws credentials
  sudo: yes
  sudo_user: "{{deploy_user}}"
  file: path="~/.aws" state=directory

- name: create aws credentials
  sudo: yes
  sudo_user: "{{deploy_user}}"
  template: src=config.j2 dest="~/.aws/config"