- name: Install boto3
  apt: name=python-boto state=present

- name: Create backups directory
  sudo_user: "{{ deploy_user }}"
  file: path=/home/{{deploy_user}}/backups state=directory

- name: Copy dumper.go
  copy: src=dumper.go dest=/home/{{deploy_user}}/dumper.go owner="{{ deploy_user }}"

- name: Copy dumper config
  template: src=dumper.json.j2 dest=/home/{{deploy_user}}/dumper.json owner="{{ deploy_user }}"

- name: Setup dumper cron task
  cron: name="influxdb backup" 
        minute=0
        hour=5
        user="{{ deploy_user }}"
        job="/bin/bash -l -c 'go run /home/{{deploy_user}}/dumper.go --config=/home/{{deploy_user}}/dumper.json'"