---
- name: Checking installed version of erlang
  shell: erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell | grep -o "{{ erlang_check_version }}"
  register: _installed
  ignore_errors: True

- name: Download erlang
  get_url: "url={{erlang_url}} dest={{erlang_tmp_path}}.tar"
  when: _installed.rc == 1

- name: Extract erlang
  command: tar -zxf "{{erlang_tmp_path}}.tar"
  when: _installed.rc == 1

- name: Make, configure, and install erlang
  command: "{{item}} chdir={{erlang_name}}"
  with_items:
    - ./configure
    - make
    - sudo make install
  when: _installed.rc == 1