---
- name: Development setup
  hosts: dev
  user: vagrant
  sudo: true
  roles:
    - { role: 'common_setup', tags:['initial'] }
    - { role: aws_cli, tags: ['aws'] }
    - { role: 'erlang', tags: ['erlang'] }
    - { role: 'golang', tags: ['go'] }
    - { role: 'influxdb', tags: ['influxdb'] }
    - { role: 'influx_setup', tags: ['influx_setup'] }
    - { role: 'influx_backup', tags: ['influx_backup'] }
