---
- name: Selectel setup
  hosts: selectel
  sudo: yes 
  remote_user: root
  gather_facts: True
  vars:
    deliverly:
      force_clean: true
  roles:
    - { role: common_setup, tags:['initial'] }
    - { role: deploy_user, tags: ['user'] }
    - { role: erlang, tags: ['erlang'] }
    - { role: influxdb, tags: ['influxdb'] }
    - { role: influx_setup, tags: ['influx_setup'] }
    - { role: tb_presence, tags: ['tb_presence'] }